# use_frameworks!

inhibit_all_warnings!

platform :ios, '8.0'

target 'ATShareView_Example' do
  pod 'ATShareView', :path => '../'

  target 'ATShareView_Tests' do
    inherit! :search_paths

    
  end
end
